{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/part-of: noona
{{- end }}